# Generated by Django 5.0 on 2025-09-28 02:19

from django.db import migrations


def migrate_pending_to_applied(apps, schema_editor):
    """Migrate existing 'pending' applications to 'applied' status"""
    Application = apps.get_model('jobs', 'Application')
    
    # Update all applications with 'pending' status to 'applied'
    Application.objects.filter(status='pending').update(status='applied')
    
    # Also update any other old statuses that might exist
    Application.objects.filter(status='reviewed').update(status='review')
    Application.objects.filter(status='accepted').update(status='offer')
    Application.objects.filter(status='rejected').update(status='closed')


def reverse_migration(apps, schema_editor):
    """Reverse the migration (convert back to old statuses)"""
    Application = apps.get_model('jobs', 'Application')
    
    # Convert back to old status names
    Application.objects.filter(status='applied').update(status='pending')
    Application.objects.filter(status='review').update(status='reviewed')
    Application.objects.filter(status='offer').update(status='accepted')
    Application.objects.filter(status='closed').update(status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_update_application_status'),
    ]

    operations = [
        migrations.RunPython(migrate_pending_to_applied, reverse_migration),
    ]
