# Generated by Django 5.2.6 on 2025-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_locationcoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcoordinate',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationcoordinate',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
