# Generated by Django 5.2.6 on 2025-09-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to all recruiters'), ('recruiters_only', 'Recruiters Only - Visible to registered recruiters'), ('private', 'Private - Only visible to you')], default='public', help_text='Control who can see your profile', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Allow recruiters to see your contact information'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Allow recruiters to see your education history'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_experience',
            field=models.BooleanField(default=True, help_text='Allow recruiters to see your work experience'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_resume',
            field=models.BooleanField(default=True, help_text='Allow recruiters to download your resume'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_social_links',
            field=models.BooleanField(default=True, help_text='Allow recruiters to see your social media links'),
        ),
    ]
