# Generated by Django 5.2.6 on 2025-09-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekerprofile_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to all recruiters'), ('private', 'Private - Only visible to you')], default='public', help_text='Control who can see your profile', max_length=20),
        ),
    ]
