# Generated by Django 5.2.6 on 2025-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobseekerprofile_profile_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='commute_radius',
            field=models.PositiveIntegerField(choices=[(5, '5 miles'), (10, '10 miles'), (15, '15 miles'), (25, '25 miles'), (50, '50 miles'), (100, '100 miles')], default=25, help_text='Preferred maximum commute distance in miles'),
        ),
    ]
